#import "CanvasModule.h"

#import <ReactCommon/RCTTurboModule.h>
#import <ReactCommon/RCTTurboModuleWithJSIBindings.h>

// Generated by codegen from src/NativeCanvasModule.ts (umbrella named after
// codegenConfig.name = "CanvasViewSpec").
#import <CanvasViewSpec/CanvasViewSpec.h>
#import <CanvasViewSpecJSI.h>

#import "CanvasInstaller.h"

using namespace facebook;

@interface CanvasModule () <NativeCanvasModuleSpec, RCTTurboModuleWithJSIBindings>
@end

@implementation CanvasModule

RCT_EXPORT_MODULE(CanvasModule)

// Spec method. The real work happens in installJSIBindingsWithRuntime: below,
// which the TurboModule manager calls when this module is constructed. This
// just lets JS confirm the module exists / force construction.
- (NSNumber *)install
{
  return @YES;
}

- (void)installJSIBindingsWithRuntime:(jsi::Runtime &)runtime
                          callInvoker:(const std::shared_ptr<react::CallInvoker> &)callInvoker
{
  rncanvas::installCanvasApi(runtime);
}

- (std::shared_ptr<react::TurboModule>)getTurboModule:(const react::ObjCTurboModule::InitParams &)params
{
  return std::make_shared<react::NativeCanvasModuleSpecJSI>(params);
}

@end
